In [2]:
from transformers import AutoModelForSequenceClassification, AutoTokenizer

#Load the model and tokenizer from the saved paths
model = AutoModelForSequenceClassification.from_pretrained('/home/kristina/code/g0zzy/stress_sense/models/dlbertfinal')
tokenizer = AutoTokenizer.from_pretrained('/home/kristina/code/g0zzy/stress_sense/models/dlbertfinal')

/home/kristina/.pyenv/versions/3.10.6/envs/stress_sense/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:

import torch
# Create a function to get predictions from the model
def get_prediction(text, model, tokenizer, device):
    inputs = tokenizer(text, return_tensors='pt', truncation=True, padding=True)
    inputs = {k: v.to(device) for k, v in inputs.items()}
    outputs = model(**inputs)
    _, predicted = torch.max(outputs.logits, dim=1)
    predictions = torch.nn.functional.softmax(outputs.logits, dim=-1)

    print(f"probabilities: \n\t{predictions}")
    print(f"id2label: \n\t{model.config.id2label}")
    print(f"predictions:")
    for _id, label in model.config.id2label.items():
        print(f"\t{label:<7}:\t{round(float(predictions[0][_id]), 3)}")
    return predicted.item(), predictions


In [4]:
test_texts = ["I don't know if I should be happy or sad",
    "I want to kill myself",
             "I have three deadlines tomorrow, and I don’t even know where to start.",
            "Every time my phone buzzes, I feel a knot in my stomach.",
            "She’s been awake for two nights straight, worrying about her exams.",
            "I feel like I’m carrying the weight of the world on my shoulders.",
            "Even small problems feel overwhelming right now.",
            "He’s smiling on the outside, but inside he’s breaking down.",
            "No matter how much I do, it never feels like enough.",
            "My chest tightens every time I think about what could go wrong.",
            "I can’t stop overthinking, even when I’m exhausted.",
            "It feels like I’m running in circles with no way out."]

In [5]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model.to(device)

BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSdpaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e

In [6]:
class_labels = {
    0: 'Anxiety',
    1: 'Normal',
    2: 'Stress',
}

In [7]:
for text in test_texts:
    predicted_class, predictions = get_prediction(text, model, tokenizer, device)
    print(f'Text: {text}')
    print(f'Predicted Class: {class_labels[predicted_class]}')

    predictions_list = predictions.tolist()
    max_index = predictions_list[0].index(max(predictions_list[0]))
    predicted_probability = predictions_list[0][max_index]
    print(f'Predicted Probability: {predicted_probability}')
    print('---')

probabilities: 
	tensor([[0.0014, 0.9908, 0.0078]], grad_fn=<SoftmaxBackward0>)
id2label: 
	{0: 'LABEL_0', 1: 'LABEL_1', 2: 'LABEL_2'}
predictions:
	LABEL_0:	0.001
	LABEL_1:	0.991
	LABEL_2:	0.008
Text: I don't know if I should be happy or sad
Predicted Class: Normal
Predicted Probability: 0.9908033609390259
---
probabilities: 
	tensor([[0.0013, 0.0029, 0.9958]], grad_fn=<SoftmaxBackward0>)
id2label: 
	{0: 'LABEL_0', 1: 'LABEL_1', 2: 'LABEL_2'}
predictions:
	LABEL_0:	0.001
	LABEL_1:	0.003
	LABEL_2:	0.996
Text: I want to kill myself
Predicted Class: Stress
Predicted Probability: 0.9957901835441589
---
probabilities: 
	tensor([[0.0016, 0.0229, 0.9755]], grad_fn=<SoftmaxBackward0>)
id2label: 
	{0: 'LABEL_0', 1: 'LABEL_1', 2: 'LABEL_2'}
predictions:
	LABEL_0:	0.002
	LABEL_1:	0.023
	LABEL_2:	0.976
Text: I have three deadlines tomorrow, and I don’t even know where to start.
Predicted Class: Stress
Predicted Probability: 0.9755101799964905
---
probabilities: 
	tensor([[0.0218, 0.1445, 0.8337]]

/tmp/ipykernel_342044/1138513180.py:14: UserWarning: Converting a tensor with requires_grad=True to a scalar may lead to unexpected behavior.
Consider using tensor.detach() first. (Triggered internally at /pytorch/torch/csrc/autograd/generated/python_variable_methods.cpp:835.)
  print(f"\t{label:<7}:\t{round(float(predictions[0][_id]), 3)}")


probabilities: 
	tensor([[0.0019, 0.3937, 0.6044]], grad_fn=<SoftmaxBackward0>)
id2label: 
	{0: 'LABEL_0', 1: 'LABEL_1', 2: 'LABEL_2'}
predictions:
	LABEL_0:	0.002
	LABEL_1:	0.394
	LABEL_2:	0.604
Text: He’s smiling on the outside, but inside he’s breaking down.
Predicted Class: Stress
Predicted Probability: 0.6043537855148315
---
probabilities: 
	tensor([[4.5901e-04, 9.9152e-01, 8.0234e-03]], grad_fn=<SoftmaxBackward0>)
id2label: 
	{0: 'LABEL_0', 1: 'LABEL_1', 2: 'LABEL_2'}
predictions:
	LABEL_0:	0.0
	LABEL_1:	0.992
	LABEL_2:	0.008
Text: No matter how much I do, it never feels like enough.
Predicted Class: Normal
Predicted Probability: 0.9915176033973694
---
probabilities: 
	tensor([[0.0053, 0.0153, 0.9793]], grad_fn=<SoftmaxBackward0>)
id2label: 
	{0: 'LABEL_0', 1: 'LABEL_1', 2: 'LABEL_2'}
predictions:
	LABEL_0:	0.005
	LABEL_1:	0.015
	LABEL_2:	0.979
Text: My chest tightens every time I think about what could go wrong.
Predicted Class: Stress
Predicted Probability: 0.9793478846549988
-